= Class Scanner

Scans the class Path and generate new class and inject dependency in them , outputs a dependecy tree and the clone package at specified location https://github.com/ashish-3916/SprinklrProject/blob/main/MyProject/src/main/java/com/start/intern/ClassScanner.java#L31[ROOT]

== Usage

update the https://github.com/ashish-3916/SprinklrProject/blob/main/MyProject/src/main/java/com/start/intern/ClassScanner.java#L31[ROOT] where package is to be created 

[source,java,indent=0]
----
	 static final String ROOT = "/Users/ashish/Desktop/CreateFile/";
----

update the https://github.com/ashish-3916/SprinklrProject/blob/main/MyProject/src/main/java/com/start/Main.java#L12[BASE_PACKAGE]

[source,java,indent=0]
----
	 private static final String BASE_PACKAGE= "com.start";
----

= Spring Boot 
=== https://github.com/spring-projects/spring-boot[source] 
branch : Spring 2.7.0-1

== Building from Source
You don't need to build from source to use Spring Boot (binaries in https://repo.spring.io[repo.spring.io]), but if you want to try out the latest and greatest, Spring Boot can be built and published to your local Maven cache using the https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle wrapper].
You also need JDK 17.

[indent=0]
----
	$ ./gradlew publishToMavenLocal
----

This will build all of the jars and documentation and publish them to your local Maven cache.
It won't run any of the tests.
If you want to build everything, use the `build` task:

[indent=0]
----
	$ ./gradlew build
----
Gradle Version used for build : Azul Zulu 13.0.11

== Maven dependency 
[source,java,indent=0]
----
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
            <version>2.7.0-1</version>
        </dependency>
----
= Spring Framework 
=== https://github.com/spring-projects/spring-framework[source]
branch : Spring 5.3.20-1

== Building from Source
You don't need to build from source to use Spring Boot (binaries in https://repo.spring.io[repo.spring.io]), but if you want to try out the latest and greatest, Spring Boot can be built and published to your local Maven cache using the https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle wrapper].
You also need JDK 17.

[indent=0]
----
	$ ./gradlew publishToMavenLocal
----

This will build all of the jars and documentation and publish them to your local Maven cache.
It won't run any of the tests.
If you want to build everything, use the `build` task:

[indent=0]
----
	$ ./gradlew build
----
== Usage

update the BASE_PACKAGE_NAME in the zip

[source,java,indent=0]
----
	Class = ClassPathBeanDefinitionScanner 
 Method = protected Set<BeanDefinitionHolder> doScan(String... basePackages)
----

Gradle Version used for build : AdoptOpenJDK 1.8

== Maven dependency 
[source,java,indent=0]
----
       <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>5.3.20-1</version>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>5.3.20-1</version>
        </dependency>
----
